apiVersion: apps/v1
kind: Deployment
metadata:
  name: rng-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rng-app
  template:
    metadata:
      labels:
        app: rng-app
    spec:
      containers:
      - name: rng-app
        image: <DOCKERHUB_USERNAME>/random-number-generator:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.25"
            memory: "256Mi"
        args:
        - "your-command-here"



# kubectl apply -f app-deployment.yaml 