apiVersion: v1
kind: Service
metadata:
  name: grafana-svc1
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-svc2
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3000
  type: NodePort
  
# kubectl apply -f service_grafana.yaml 